### ISSUE TITLE
Improve design of website.

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/ai-stories#2]
I require help to improve the design of the website: [ai-stories.kendalldoescoding.gq](http://ai-stories.kendalldoescoding.gq/)... 

Suggestions
- Can change the color of text.
- Can remove underline from hyperlink.
- Can color the hyperlink.
- Can add a gradient background.
- Can change the color of background.

![image](https://user-images.githubusercontent.com/84712013/182899646-57bf6926-d925-4da2-a809-0df3142caa16.png)

**Comment by Joshua-Nweze** [comment]
I will get it done

**Comment by KendallDoesCoding** [comment]
> I will get it done

Sure

**Comment by KendallDoesCoding** [comment]
fixed in #3
